### ISSUE TITLE
Release with version tag and npm package update

### ISSUE THREAD

**Issue by sachalifs** [component/t#5]
Is there a chance someone could do this? I would really appreciate it.

**Comment by defunctzombie** [comment]
ping @visionmedia as he is the one with the npm rights

**Comment by cristiandouce** [comment]
:+1:

I'm using this for server and client.

As a `component` for the SPA... and as a `package` for server side email translations...

Sadly `npm` does not resolve github urls as fast as npm's... So it would be great to have updated the package as well!

**Comment by Swatinem** [comment]
Yup, @visionmedia is very busy, wrote him a mail a week or two ago about this. I would love be able to publish to npm, thats the thing blocking a release.

**Comment by juliangruber** [comment]
you can just install your npm fork: `npm install swatinem/t`

**Comment by Swatinem** [comment]
I’m happy as I’m using it in component only with `"*"` as version :-)
Would be nice to make an official release though for all the others using it in node or browserify.

**Comment by tj** [comment]
boo npm. releasing

**Comment by cristiandouce** [comment]
:dancer:
